---
name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/sync_labels.yml

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Run label suncer
        uses: micnncim/action-label-syncer@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}