name: Wordpress-Tekton-atK8s-inGCP

on:
  #push:
  #  paths:
  #    - 'terraform/**'
  #    - '.github/workflows/TerraformGCP.yml'
  #  branches:
  #    - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BUCKET_NAME: mondybucketgcp # Replace with your bucket name. !!
  SA_NAME: gsp-s-account@striped-torus-390614.iam.gserviceaccount.com
  CLUSTER_NAME: mondyspout-clusterk8s # Replace with your cluster name (your_cluster_name-clusterk8s).
  REGION: us-central1
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REPO: VentureStudent/wordpress-cloud-k8s

jobs:
  terraform-CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform_gcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Decode credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials_file.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud config set account ${SA_NAME}
          gcloud auth activate-service-account --key-file=credentials_file.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - name: Create bucket if dosn't exists
        env:
          SCRIPT_DIR: ${{ github.workspace }}/terraform_gcp/scripts
        run: bash  $SCRIPT_DIR/create-bucket.sh

      - name: terraform init
        run: terraform init

      - name: terraform plan
        id: plan
        run: terraform plan -lock=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: terraform apply
        if: "!contains(github.event.head_commit.message, 'destroy')"
        run: terraform apply -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: Delete Webhook
        if: contains(github.event.head_commit.message, 'destroy')
        env:
          SCRIPT_DIR: ${{ github.workspace }}/terraform_gcp/scripts
        run: |
          bash $SCRIPT_DIR/del-webhook.sh
      - name: Terraform Destroy
        if: contains(github.event.head_commit.message, 'destroy')
        run: terraform destroy -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
